Vagrant.configure("2") do |config|
  # Используем образ Ubuntu 18.04
  config.vm.box = "ubuntu/bionic64"

  # Обновление пакетов и установка необходимых пакетов
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip postgresql python-psycopg2 libpq-dev
    sudo pip3 install psycopg2 Django
  SHELL

  # Копирование пустого файла на виртуальную машину
  config.vm.provision "file", source: "./copy.txt", destination: "~/copy.txt"

end
